### ISSUE TITLE
Cowsay Task_8 Autograder Failing, but correct output [STUCK]

### ISSUE THREAD

**Issue by jordancallahan** [code4policy/2023#1]
**Which assignment are you stuck on?** (if appropriate, post a link to your private repository for that assignment)

Cowsay assignment, task 8

https://github.com/code4policy/cowsay-jordancallahan

**Describe the step on which you are stuck**

A clear and concise description of what step/task you are stuck on, what you expected to happen and possible reasons for failure (if applicable).

I've navigated to the folder where the cowsay files are in my machine, and added a new "fox.cow" file with the code from the link in the assignment included.

Path to cowsay files: /opt/homebrew/Cellar/cowsay/3.04_1/share/cows

<img width="794" alt="image" src="https://user-images.githubusercontent.com/32796129/210920526-e3c21322-4980-4b1b-a587-0df467bb29f9.png">

When I commit and push all my tasks to github, I pass all of them except for task8. When I run the task locally, however, it matches with the "expected answers."

Here's a screenshot of the code snippet:

<img width="545" alt="image" src="https://user-images.githubusercontent.com/32796129/210920643-af8f0f4d-20a2-4010-8a6a-7f32653735ab.png">

Here's a screenshot of the output from that snippet:

<img width="246" alt="image" src="https://user-images.githubusercontent.com/32796129/210920696-4edf65a9-2883-4bb7-8e6d-d846d6d93885.png">

And here's a screenshot of the expected answer:

<img width="244" alt="image" src="https://user-images.githubusercontent.com/32796129/210920776-944da7d8-bda5-4b0f-a5ea-a6a75b845917.png">

As you can see, they match.

When the autograder runs, however, I get the following error:

<img width="709" alt="image" src="https://user-images.githubusercontent.com/32796129/210920876-08fdb526-ce70-43c1-b780-3a9b79d2d933.png">

The output is different than what is being produced on my machine. Is the issue with how I've installed the fox file?

**How to Reproduce + screenshots or code-snippets if appropriate**

Above!

Steps to reproduce the behavior (if applicable) and/or screenshots or code-snippets that help to explain your problem.

**Additional context**

**Comment by jordancallahan** [comment]
As an update, I downloaded the fox.cow file using wget into my repository, and updated the code snippet to reference the file in the current working directory.

I now see the correct fox output in the autograder, but it's still failing. Screenshot below:

<img width="659" alt="image" src="https://user-images.githubusercontent.com/32796129/211044186-76b8e181-e880-4f08-b63b-fb523ee16f70.png">

Current file structure and code snippet:

<img width="759" alt="image" src="https://user-images.githubusercontent.com/32796129/211044283-ebed1876-95d6-42bd-8d6a-ccbadcc3420c.png">

And output:

<img width="265" alt="image" src="https://user-images.githubusercontent.com/32796129/211044354-720b4d9b-2e56-4c41-9b4a-d3665b77f87a.png">

**Comment by pcsong33** [comment]
Hi Jordan, can you try renaming the file to fox2.cow, and referencing fox2.cow in your task_8.sh file? I think there's a default fox that gets called when the autograder runs/

**Comment by jordancallahan** [comment]
> 

Hi Patrick, I renamed the file and updated the reference, and the autograder still fails.

**Comment by pcsong33** [comment]
Hi Jordan, let's try one more thing: can you save the new fox file locally (perhaps somewhere in your Development directory), and reference the local file when you ran your cowsay command in the task_8.sh file?

If this doesn't work, don't worry about the autograder giving an incorrect output: since you're able to get the correct output locally, we'll give full credit for this task.

**Comment by jordancallahan** [comment]
Here's the snippet:

`cowsay -f "/opt/homebrew/Cellar/cowsay/3.04_1/share/cows/fox.cow" "Hello, world!"`

I'll close this issue now, if that's okay. Thank you!
