### ISSUE TITLE
Simple Website - Making Repo Public 

### ISSUE THREAD

**Issue by manvika-g** [code4policy/2023#4]
**Which assignment are you stuck on?** (if appropriate, post a link to your private repository for that assignment)
NA

**Describe the step on which you are stuck**
Part 2 of the problem that asks to make the website public 

A clear and concise description of what step/task you are stuck on, what you expected to happen and possible reasons for failure (if applicable).
<img width="1111" alt="Screenshot 2023-01-07 at 8 06 46 AM" src="https://user-images.githubusercontent.com/121726399/211152827-77a0bc1f-a860-4c74-99b1-9119c4412414.png">

Not able to make the website public as it says that I have to take permission from the owner and that Github pages is not nables

**How to Reproduce + screenshots or code-snippets if appropriate**
Go to Settings

Steps to reproduce the behavior (if applicable) and/or screenshots or code-snippets that help to explain your problem.
NA

**Additional context**
NA 

everything else in the assignment seems to be working well!! thank you

**Comment by dmil** [comment]
If you hit "general" on the left side, and scroll all the way down to the "Danger Zone" you can set the repo to public. Then come back to this page and it should allow you to serve the page!

**Comment by manvika-g** [comment]
Thank you! Working, now :)
