### ISSUE TITLE
Picture won't render

### ISSUE THREAD

**Issue by JaimeEnriqueForero** [code4policy/2023#5]
here is the code:
 <img src=”images/jaime12.jpg”/>

here its what the console at the browser says:
The character encoding of the document was not declared, so the encoding was guessed from content. The character encoding needs to be declared in the Content-Type HTTP header, using a meta tag, or using a byte order mark. index.html

**Comment by dmil** [comment]
The image isn't rendering here. But I met with Jaime in person and the issue was resolved. The problem was that he had copied and pasted from slack and it was using the curly double quotes instead of the normal/straight ones `"`. This can happen when copy/pasting from the web.
